version: '0.0.{build}'
image: Visual Studio 2017
init:
  - choco install docfx -y
build_script:
  - docfx Documentation/docfx.json
after_build:
  - 7z a site.zip Documentation
test: off
artifacts:
  - path: site.zip
    name: docs
